title: "DSA Learning Hub"
description: "Data Structures and Algorithms Implementations"
baseurl: ""
url: ""

# Collections with dates
collections:
  python:
    output: true
    permalink: /python/:path/
  java:
    output: true
    permalink: /java/:path/
  cpp:
    output: true
    permalink: /cpp/:path/

# Default front matter for all pages
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
      date: 2024-03-20  # Default date if not specified 