title: AI ML DL
description: A GitHub Pages site powered by Jekyll
baseurl: "/DSA"  # Since it's inside 'docs/' folder
url: "https://nshravanreddy.github.io"  # Your repo URL
theme: minima

plugins:
  - jekyll-feed
  - jekyll-sitemap
